### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by magni-** [pr-mpt/actions-assert#64]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Seems like all that should be needed is updating `actions/core` to `1.10.0`? https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#1100

**Comment by shrink** [comment]
@magni- thank you very much for letting me know! I've updated `@actions/core` and the node version to deal with the upcoming deprecation. I've released this upgrade as `v4.0.0` so you may replace `@v3` with `@v4` in your actions :) Let me know if you notice anything else that needs to be addressed!
